# Generated by Django 5.1.3 on 2024-12-08 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='nickname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
